import React, { useState, useEffect, useRef } from "react";
const formData1 = [ 
    { label: ( 
    <> 
    Company ID 
    <span className="text-[#7C7D7D] text-[12px]">
        (5 Digit Auto Generated by the System)
    </span> 
    </> 
    ), 
    placeholder: "Enter company ID...", 
    },
    { label: "Company Name", placeholder: "Enter company name..." },
    { label: "Company ID", placeholder: "Enter company id..." },
    ]; 

const formData2 = [ 
    { label: "Primary Color", placeholder: "#000000" }, 
    { label: "Secondary Color", placeholder: "#000000" },
    { label: "Company HQ", placeholder: "Enter company HQ..." }, 
    { label: "Company Description", placeholder: "Enter company description..." }, 
    { label: "Company’s Base Year Revenue", placeholder: "Enter company’s base year revenue..." },
    { label: "Company Product", placeholder: "Enter company product..." },
    { label: "Company Country Product Mfg.", placeholder: "Enter company country product mfg..." },
    { label: "Company Country Product Sell to", placeholder: "Enter company country product sell to..." }, 
    { label: "Company Country Product Strategy", placeholder: "Enter company country product strategy..." },
    { label: "Company Country Strategy", placeholder: "Enter company country strategy..." }, 
    { label: "Company Country Strategy Weighting", placeholder: "Enter company country strategy weighting..." }, 
    { label: "Company Country Strategy Win Probability", placeholder: "Enter company country strategy win probability..." }, 
]; 
const Form = () => { 
        const [showForm, setShowForm] = useState(false); 
        const formRef = useRef(null); 

    useEffect(() => { 
        const handleClickOutside = (event) => { 
            if (formRef.current && !formRef.current.contains(event.target)) { 
                setShowForm(false);
            } 
        }; 
            if (showForm) {
                document.addEventListener("mousedown", handleClickOutside); 
            } 
            return () => { 
                document.removeEventListener("mousedown", handleClickOutside);
            }; 
        }, [showForm]); 

            const InputField = ({ label, placeholder }) => ( 

                <div className="flex flex-col"> 
                <label className="text-[15px] text-[#344054]">{label}</label> 
                <input type="text" placeholder={placeholder} className="mt-1 px-2 py-1 border border-[#D0D5DD] rounded-md placeholder-[#667085] text-[14px]" />
                </div> 
            ); 
            return ( 
                <> 
                <button onClick={() => setShowForm(true)} className="bg-[#0E66CE] text-[#E6E6E6] px-4 py-2 rounded-md" > Add Company </button>

                 {showForm && ( 
                    <div className="fixed inset-0 flex items-center justify-center bg-gray-200"> 
                    <div ref={formRef} className="bg-white rounded-lg p-6 w-full max-w-2xl shadow-lg relative" > 
                        <div className="flex justify-between items-center ">
                             <div className="text-base font-semibold text-[#101828]"> Add Company </div> 
                             <button onClick={() => setShowForm(false)} className="text-2xl text-[#98A2B3]" > × </button> 
                             </div> <div className="text-[#475467] text-[15px] mb-7"> Create profiles for human-controlled businesses. </div>
                              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[18px] mb-2"> 
                                {formData1.map((field, index) => ( 
                                    <InputField key={index} label={field.label} placeholder={field.placeholder} /> ))}
                              </div> 
                             <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                                 {formData2.map((field, index) => ( <InputField key={index} label={field.label} placeholder={field.placeholder} /> ))} 
                             </div> 
                             <div className="grid grid-cols-2 gap-2 mt-6">
                                 <button className="bg-white border border-[#D0D5DD] px-4 py-2 rounded-md text-[#344054]" onClick={() => setShowForm(false)} > Cancel </button> 
                                 <button className="bg-[#0E66CE] border border-[#0E66CE] px-4 py-2 rounded-md text-white text-[18px]"> Add </button>
                             </div> 
                             </div> 
                             </div>
                )}
                    </> 
                    ); 
            }; 
export default Form;